[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "District Energy Model"
authors = [{name = "HSLU CC TES", email = "ueli.schilt@hslu.ch"}]
dynamic = ["version", "description"]
